### ISSUE TITLE
第 6.4 章筆誤

### ISSUE THREAD

**Issue by likueimo** [whyjz/GMT-tutorials#4]
嗨嗨 學長您好
這邊看到簡單筆誤

在第 6.4 部分
http://gmt-tutorials.org/pen_and_painting.html#id9

>第一段：海底地形圖 (psimage)
第二段：格線 (可以併在 psimage -B 的選項來畫)
第三段：國家邊界與著色 (pscoast)

第一段的 psimage 我猜應是 grdimage ?
第二段的 psimage 我猜應是 pscoast ?

**Comment by whyjz** [comment]
嗨，

感謝您的指正！抱歉拖了點時間回信，我從上禮拜起前往中美洲渡假，要到八月十號才有機會使用我的電腦，屆時就會修正這些錯誤。或是如果您願意的話，也可以丟個
pull request 給我來合併。再次感謝！

祝 好
懷傑

kmo <notifications@github.com> 於 2018年7月28日 週六 13:32 寫道：

**Comment by likueimo** [comment]
第一次 pull request
謝謝學長給這個機會 XD

**Comment by whyjz** [comment]
Done! Thanks a lot kmo!
